export const PRODUCT = {
    FETCH_LIST_PRODUCT: "PRODUCT_FETCH_LIST_PRODUCT"
};

export const POS_ACTION = {
    FETCH_ALL: 'POS_ACTION_FETCH_ALL',
    ADD_OPTIMISTIC: 'POS_ACTION_ADD_OPTIMISTIC',
    ADD: 'POS_ACTION_ADD'
}

export const AUTH_ACTION = {
    CURRENT_USER: "AUTH_ACTION_CURRENT_USER"
};

export const INVENTORY_ACTION = {
    FETCH_USER_PRODUCT: "INVENTORY_ACTION_FETCH_USER_PRODUCT",
    FETCH_INVENTORY_HISTORY: "INVENTORY_FETCH_INVENTORY_HISTORY"
};

export const DISCOUNT_ACTION = {
    CHANGE_AMOUNT: 'DISCOUNT_ACTION_CHANGE_AMOUNT',
    APPLY_DATE: 'DISCOUNT_ACTION_APPLY_DATE',
    DUE_DATE: 'DISCOUNT_ACTION_DUE_DATE',
    PICK_POS: 'DISCOUNT_ACTION_PICK_POS'
}