export const PRODUCT = {
    FETCH_LIST_PRODUCT: "PRODUCT_FETCH_LIST_PRODUCT"
};

export const AUTH_ACTION = {
    CURRENT_USER: "AUTH_ACTION_CURRENT_USER"
};

export const INVENTORY_ACTION = {
    FETCH_USER_PRODUCT: "INVENTORY_ACTION_FETCH_USER_PRODUCT"
};