export const PRODUCT = {
    FETCH_LIST_PRODUCT: "PRODUCT_FETCH_LIST_PRODUCT",
    UPDATE_PRODUCT: 'PRODUCT_UPDATE_PRODUCT'
};

export const CATEGORY_ACTION = {
    UPDATE_CATEGORY: 'CATEGORY_UPDATE_CATEGORY'
}

export const POS_ACTION = {
    FETCH_ALL: 'POS_ACTION_FETCH_ALL',
    ADD_OPTIMISTIC: 'POS_ACTION_ADD_OPTIMISTIC',
    ADD: 'POS_ACTION_ADD',
    UPDATE: 'POS_ACTION_UPDATE',
    DEACTIVATE: "POS_ACTION_DEACTIVATE"
}

export const AUTH_ACTION = {
    CURRENT_USER: "AUTH_ACTION_CURRENT_USER"
};

export const INVENTORY_ACTION = {
    FETCH_USER_PRODUCT: "INVENTORY_ACTION_FETCH_USER_PRODUCT",
    UPDATE_PRODUCT: 'INVENTORY_ACTION_UPDATE_PRODUCT',
    FETCH_INVENTORY_HISTORY: "INVENTORY_FETCH_INVENTORY_HISTORY"
};

export const INVENTORY_ACTIVITY_ACTION = {
    FETCH_LOGS: 'INVENTORY_ACTIVITY_ACTION_FETCH_LOGS',
    FETCH_INVENTORY_ACTIVITY_COMPANY: 'INVENTORY_ACTIVITY_ACTION_FETCH_INVENTORY_ACTIVITY_COMPANY'
}

export const DISCOUNT_ACTION = {
    FETCH_ALL_DISCOUNT: 'DISCOUNT_ACTION_FETCH_ALL_DISCOUNT',
    CHANGE_AMOUNT: 'DISCOUNT_ACTION_CHANGE_AMOUNT',
    CHANGE_OPTION: 'DISCOUNT_ACTION_CHANGE_OPTION',
    APPLY_DATE: 'DISCOUNT_ACTION_APPLY_DATE',
    DUE_DATE: 'DISCOUNT_ACTION_DUE_DATE',
    PICK_POS: 'DISCOUNT_ACTION_PICK_POS',
    PICK_PRODUCTS: 'DISCOUNT_ACTION_PICK_PRODUCTS'
}